# Generated by Django 5.2.16 on 2026-07-29 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attemptquestion_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='accounts.attemptquestion'),
        ),
    ]
