# Generated by Django 5.2.16 on 2026-07-31 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentanswer_attempt_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='accounts.assessmentattempt')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='accounts.enrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
