# Generated by Django 5.2.16 on 2026-08-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.school'),
        ),
    ]
