# Generated by Django 5.2.16 on 2026-07-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_currency_course_is_free_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',)},
        ),
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Final Assessment', max_length=180)),
                ('instructions', models.TextField(blank=True, default='Answer every question and select one answer for each question.')),
                ('passing_score', models.PositiveSmallIntegerField(default=80, help_text='Minimum percentage required to pass.')),
                ('questions_per_attempt', models.PositiveSmallIntegerField(default=20, help_text='Number of questions presented in each attempt.')),
                ('maximum_attempts', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty to allow unlimited attempts.', null=True)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course assessment',
                'verbose_name_plural': 'Course assessments',
                'ordering': ('course__title',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown after the attempt.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.courseassessment')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='courses.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_question_order_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_answer_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='one_correct_answer_per_question'),
        ),
    ]
