# Generated by Django 5.2.16 on 2026-08-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_backfill_school_students'),
    ]

    operations = [
    ]
